insert overwrite table ${DATABASE}.${TABLE_NAME}
select 
	CREDITORG_SBCODE,
	CREDITORG_SNAME,
	REQUESTTYPENAME,
	SPOTTYPENAME,
	SCLIENTPIN,
	CONVERSIONDATE,
	IDCASHREQUEST,
	ISBROKEN,
	ISRETURN,
	WORTHNAME,
	SCATEGORY,
	SCURRENCY,
	cast(SNOMINAL as Decimal(38,2)) as SNOMINAL,
	SNOMINALTYPE,
	COUNTFROMCLIENT,
	cast(SUMFROMCLIENT as Decimal(38,2)) as SUMFROMCLIENT,
	COUNTTOCLIENT,
	cast(SUMTOCLIENT as Decimal(38,2)) as SUMTOCLIENT
from ${TMP_DATABASE}.${TABLE_NAME}_tmp;